{
  pkgs,
  lib,
  versions,
  pythonOverrides,
  cudaSupport ? false,
}:
let
  python = pkgs.python312.override { packageOverrides = pythonOverrides; };

  vendored = import ./vendored-packages.nix { inherit pkgs python versions; };

  # Import custom nodes for bundling
  customNodes = import ./custom-nodes.nix {
    inherit
      pkgs
      lib
      python
      versions
      ;
  };

  comfyuiSrcRaw = pkgs.fetchFromGitHub {
    owner = "comfyanonymous";
    repo = "ComfyUI";
    rev = versions.comfyui.rev;
    hash = versions.comfyui.hash;
  };

  comfyuiSrc = pkgs.applyPatches {
    src = comfyuiSrcRaw;
    patches = [
      ../nix/patches/comfyui-mps-fp8-dequant.patch
      ../nix/patches/comfyui-ltxvideo-rotary-emb.patch
    ];
  };

  modelDownloaderDir = builtins.path {
    path = ../src/custom_nodes/model_downloader;
    name = "comfyui-model-downloader";
  };

  # Pip constraints to prevent conflicts with Nix-provided packages
  pipConstraints = pkgs.writeText "pip-constraints.txt" ''
    # Auto-generated by comfyui-nix
    # Prevents pip from overwriting Nix-provided packages with incompatible versions
    huggingface-hub<1.0
    transformers>=4.0.0
    torch>=2.0.0
    torchvision>=0.15.0
    numpy>=1.24.0
    pillow>=9.0.0
    safetensors>=0.3.0
  '';

  # Default ComfyUI-Manager configuration
  managerConfig = pkgs.writeText "comfyui-manager-config.ini" ''
    # ComfyUI-Manager configuration
    # Generated by comfyui-nix flake
    #
    # security_level: strong | normal | normal- | weak
    # network_mode: public | private | offline | personal_cloud
    #
    # personal_cloud mode relaxes security for trusted environments
    # (e.g., running on your own machine with --listen for network access)

    [default]
    security_level = normal
    network_mode = personal_cloud
  '';

  pythonRuntime = python.withPackages (
    ps:
    let
      available = pkg: lib.meta.availableOn pkgs.stdenv.hostPlatform pkg;
      # Core ComfyUI dependencies
      base = with ps; [
        pillow
        numpy
        einops
        transformers
        tokenizers
        sentencepiece
        safetensors
        aiohttp
        yarl
        pyyaml
        requests
        scipy
        tqdm
        psutil
        alembic
        sqlalchemy
        av
        pydantic-settings
      ];
      # ComfyUI Manager and common custom node dependencies
      extras =
        with ps;
        [
          pip # Required for comfyui-manager security check
          uv # Required for comfyui-manager package management
          chardet # Required for comfyui-manager to read requirements.txt files
          pygithub # Required for comfyui-manager GitHub integration
          typer # Required for comfyui-manager CLI
          matrix-nio # Optional: enables ComfyUI-Manager matrix sharing feature
          opencv4 # Required by many custom nodes for image processing (cv2)
          imageio-ffmpeg # Required by VideoHelperSuite and other video nodes
          # Impact Pack dependencies
          scikit-image # Image processing (skimage)
          piexif # EXIF metadata handling
          matplotlib # Plotting and visualization
          dill # Extended pickling
          segment-anything # Meta AI SAM model
          sam2 # Meta AI SAM 2 model
          # KJNodes dependencies
          mss # Screen capture
          # General ML utilities
          accelerate # HuggingFace Accelerate for distributed training/inference
          # ComfyUI-GGUF dependencies
          gguf # GGUF file format support
          protobuf # Required for GGUF tokenizer support
          # LTXVideo dependencies
          diffusers # Diffusion models
          huggingface-hub # HuggingFace Hub
          timm # PyTorch Image Models
          # Florence2 dependencies
          peft # Parameter-efficient fine-tuning
          # MMAudio dependencies
          librosa # Audio processing
          torchdiffeq # Differential equations solver
          omegaconf # Configuration management
          open-clip-torch # OpenCLIP
          ftfy # Text encoding fixes
          # PuLID dependencies
          onnxruntime # ONNX runtime
        ]
        ++ [ ps."color-matcher" ]; # Color matching (hyphenated name needs quoting)
      # torch is overridden at the base level in python-overrides.nix when cudaSupport=true
      # so ps.torch is already CUDA-enabled when building with CUDA support
      torchPackages = lib.optionals (ps ? torch && available ps.torch) [ ps.torch ];
      optionals =
        torchPackages
        ++ lib.optionals (ps ? torchvision && available ps.torchvision) [ ps.torchvision ]
        ++ lib.optionals (ps ? torchaudio && available ps.torchaudio) [ ps.torchaudio ]
        ++ lib.optionals (ps ? torchsde && available ps.torchsde) [ ps.torchsde ]
        ++ lib.optionals (ps ? kornia && available ps.kornia) [ ps.kornia ]
        ++ lib.optionals (ps ? pydantic && available ps.pydantic) [ ps.pydantic ]
        ++ lib.optionals (ps ? spandrel && available ps.spandrel) [ ps.spandrel ]
        ++ lib.optionals (ps ? gitpython && available ps.gitpython) [ ps.gitpython ]
        ++ lib.optionals (ps ? toml && available ps.toml) [ ps.toml ]
        ++ lib.optionals (ps ? rich && available ps.rich) [ ps.rich ]
        ++ lib.optionals (ps ? "comfy-cli" && available ps."comfy-cli") [ ps."comfy-cli" ]
        # Linux-only packages (CUDA dependencies)
        ++ lib.optionals (pkgs.stdenv.isLinux && ps ? bitsandbytes) [ ps.bitsandbytes ]
        ++ lib.optionals (pkgs.stdenv.isLinux && ps ? xformers) [ ps.xformers ]
        # Face analysis packages - work on all platforms (insightface override removes mxnet)
        ++ lib.optionals (ps ? insightface) [ ps.insightface ]
        ++ lib.optionals (ps ? facexlib) [ ps.facexlib ]
        ++ [
          vendored.comfyuiFrontendPackage
          vendored.comfyuiWorkflowTemplates
          vendored.comfyuiEmbeddedDocs
          vendored.comfyuiManager
        ];
    in
    base ++ extras ++ optionals
  );

  frontendRoot = "${pythonRuntime}/${python.sitePackages}/comfyui_frontend_package/static";

  libPath = lib.makeLibraryPath [
    pkgs.stdenv.cc.cc.lib
    pkgs.glib
    pkgs.libGL
  ];

  # Platform-specific default data directory
  # macOS: ~/Library/Application Support/comfy-ui (Apple convention)
  # Linux: ~/.config/comfy-ui (XDG convention)
  defaultDataDir =
    if pkgs.stdenv.isDarwin then
      "$HOME/Library/Application Support/comfy-ui"
    else
      "$HOME/.config/comfy-ui";

  # Platform-specific library path setup
  libraryPathSetup =
    if pkgs.stdenv.isDarwin then
      ''
        # macOS: Set DYLD_LIBRARY_PATH for dynamic libraries
        export DYLD_LIBRARY_PATH="${libPath}''${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
      ''
    else
      ''
        # Linux: Set LD_LIBRARY_PATH for dynamic libraries
        export LD_LIBRARY_PATH="${libPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

        # Add NVIDIA driver libraries if available (NixOS)
        if [[ -d "/run/opengl-driver/lib" ]]; then
          export LD_LIBRARY_PATH="/run/opengl-driver/lib:$LD_LIBRARY_PATH"
        fi
      '';

  # Platform-specific browser command
  browserCommand = if pkgs.stdenv.isDarwin then "open" else "xdg-open";

  # Minimal launcher using writeShellApplication (Nix best practice)
  comfyUiLauncher = pkgs.writeShellApplication {
    name = "comfy-ui";
    runtimeInputs =
      [
        pkgs.coreutils
        pkgs.gnused
        pkgs.git # Required for ComfyUI Manager to clone custom nodes
      ]
      ++ lib.optionals (!pkgs.stdenv.isDarwin) [
        pkgs.xdg-utils # Provides xdg-open for --open flag on Linux
      ];
    text = ''
      # Parse arguments - extract --base-directory, --open, --port, pass rest to ComfyUI
      BASE_DIR="''${COMFY_USER_DIR:-${defaultDataDir}}"
      OPEN_BROWSER=false
      PORT=8188
      COMFY_ARGS=()

      while [[ $# -gt 0 ]]; do
        case "$1" in
          --base-directory=*)
            BASE_DIR="''${1#*=}"
            shift
            ;;
          --base-directory)
            BASE_DIR="$2"
            shift 2
            ;;
          --port=*)
            PORT="''${1#*=}"
            COMFY_ARGS+=("$1")
            shift
            ;;
          --port)
            PORT="$2"
            COMFY_ARGS+=("$1" "$2")
            shift 2
            ;;
          --open)
            OPEN_BROWSER=true
            shift
            ;;
          *)
            COMFY_ARGS+=("$1")
            shift
            ;;
        esac
      done

      # Expand ~ in BASE_DIR (handles both ~/path and ~user/path)
      BASE_DIR="''${BASE_DIR/#\~/$HOME}"

      # Create directory structure (idempotent)
      mkdir -p "$BASE_DIR"/{models,output,input,user,custom_nodes,temp}
      mkdir -p "$BASE_DIR/models"/{checkpoints,loras,vae,controlnet,embeddings,upscale_models,clip,clip_vision,diffusion_models,text_encoders,unet,configs,diffusers,vae_approx,gligen,hypernetworks,photomaker,style_models}

      # Link our bundled custom nodes
      # Remove stale directories if they exist but aren't symlinks
      for node_dir in "model_downloader" "ComfyUI-Impact-Pack" "rgthree-comfy" "ComfyUI-KJNodes" "ComfyUI-GGUF" "ComfyUI-LTXVideo" "ComfyUI-Florence2" "ComfyUI_bitsandbytes_NF4" "x-flux-comfyui" "ComfyUI-MMAudio" "PuLID_ComfyUI" "ComfyUI-WanVideoWrapper"; do
        if [[ -e "$BASE_DIR/custom_nodes/$node_dir" && ! -L "$BASE_DIR/custom_nodes/$node_dir" ]]; then
          rm -rf "$BASE_DIR/custom_nodes/$node_dir"
        fi
      done

      # On macOS, remove Linux-only nodes if they were linked previously
      # Note: PuLID now works on macOS via CoreML (insightface override removes mxnet dependency)
      if [[ "$(uname)" == "Darwin" ]]; then
        rm -f "$BASE_DIR/custom_nodes/ComfyUI_bitsandbytes_NF4" 2>/dev/null || true
      fi

      # Clean up stale read-only web extension directories (from Nix store)
      if [[ -d "$BASE_DIR/web/extensions" ]]; then
        find "$BASE_DIR/web/extensions" -maxdepth 1 -type d ! -writable -exec rm -rf {} \; 2>/dev/null || true
      fi

      # Link bundled nodes
      if [[ ! -e "$BASE_DIR/custom_nodes/model_downloader" ]]; then
        ln -sf "${modelDownloaderDir}" "$BASE_DIR/custom_nodes/model_downloader"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-Impact-Pack" ]]; then
        ln -sf "${customNodes.impact-pack}" "$BASE_DIR/custom_nodes/ComfyUI-Impact-Pack"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/rgthree-comfy" ]]; then
        ln -sf "${customNodes.rgthree-comfy}" "$BASE_DIR/custom_nodes/rgthree-comfy"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-KJNodes" ]]; then
        ln -sf "${customNodes.kjnodes}" "$BASE_DIR/custom_nodes/ComfyUI-KJNodes"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-GGUF" ]]; then
        ln -sf "${customNodes.gguf}" "$BASE_DIR/custom_nodes/ComfyUI-GGUF"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-LTXVideo" ]]; then
        ln -sf "${customNodes.ltxvideo}" "$BASE_DIR/custom_nodes/ComfyUI-LTXVideo"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-Florence2" ]]; then
        ln -sf "${customNodes.florence2}" "$BASE_DIR/custom_nodes/ComfyUI-Florence2"
      fi
      # bitsandbytes requires CUDA (Linux-only)
      if [[ "$(uname)" != "Darwin" && ! -e "$BASE_DIR/custom_nodes/ComfyUI_bitsandbytes_NF4" ]]; then
        ln -sf "${customNodes.bitsandbytes-nf4}" "$BASE_DIR/custom_nodes/ComfyUI_bitsandbytes_NF4"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/x-flux-comfyui" ]]; then
        ln -sf "${customNodes.x-flux}" "$BASE_DIR/custom_nodes/x-flux-comfyui"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-MMAudio" ]]; then
        ln -sf "${customNodes.mmaudio}" "$BASE_DIR/custom_nodes/ComfyUI-MMAudio"
      fi
      # PuLID - face ID for consistent face generation
      # Works on all platforms: Linux uses CUDA, macOS uses CoreML via onnxruntime
      if [[ ! -e "$BASE_DIR/custom_nodes/PuLID_ComfyUI" ]]; then
        ln -sf "${customNodes.pulid}" "$BASE_DIR/custom_nodes/PuLID_ComfyUI"
      fi
      if [[ ! -e "$BASE_DIR/custom_nodes/ComfyUI-WanVideoWrapper" ]]; then
        ln -sf "${customNodes.wanvideo}" "$BASE_DIR/custom_nodes/ComfyUI-WanVideoWrapper"
      fi

      # Create default ComfyUI-Manager config if it doesn't exist
      MANAGER_CONFIG_DIR="$BASE_DIR/user/default/ComfyUI-Manager"
      MANAGER_CONFIG="$MANAGER_CONFIG_DIR/config.ini"
      if [[ ! -e "$MANAGER_CONFIG" ]]; then
        mkdir -p "$MANAGER_CONFIG_DIR"
        cp "${managerConfig}" "$MANAGER_CONFIG"
        echo "Created default ComfyUI-Manager config at $MANAGER_CONFIG"
      fi

      # Set platform-specific library paths for GPU support
      ${libraryPathSetup}

      # Configure pip to install packages to a mutable location
      # This allows ComfyUI-Manager to install custom node dependencies
      # while keeping the Nix store read-only
      export PIP_TARGET="$BASE_DIR/.pip-packages"
      export PYTHONPATH="''${PYTHONPATH:+$PYTHONPATH:}$BASE_DIR/.pip-packages"
      mkdir -p "$PIP_TARGET"

      # Prevent pip from installing packages that conflict with Nix-provided ones
      export PIP_CONSTRAINT="${pipConstraints}"

      # Set model path for custom nodes that check this env var
      # (prevents them from trying to write to the read-only Nix store)
      export COMFYUI_MODEL_PATH="$BASE_DIR/models"

      # Redirect PyTorch hub downloads to data directory
      # This prevents attempts to write to the read-only Nix store
      export TORCH_HOME="$BASE_DIR/.cache/torch"
      mkdir -p "$TORCH_HOME"

      # Redirect HuggingFace cache to data directory for model downloads
      export HF_HOME="$BASE_DIR/.cache/huggingface"
      mkdir -p "$HF_HOME"

      # Redirect facexlib model downloads to data directory
      # (facexlib is patched to respect this env var)
      export FACEXLIB_MODELPATH="$BASE_DIR/.cache/facexlib"
      mkdir -p "$FACEXLIB_MODELPATH/facexlib/weights"

      # Open browser if requested (background, after short delay)
      if [[ "$OPEN_BROWSER" == "true" ]]; then
        (sleep 3 && ${browserCommand} "http://127.0.0.1:$PORT" 2>/dev/null) &
      fi

      # Run ComfyUI directly from Nix store
      exec "${pythonRuntime}/bin/python" "${comfyuiSrc}/main.py" \
        --base-directory "$BASE_DIR" \
        --front-end-root "${frontendRoot}" \
        --database-url "sqlite:///$BASE_DIR/user/comfyui.db" \
        "''${COMFY_ARGS[@]}"
    '';
  };

  # Package wraps the launcher for installation
  comfyUiPackage = pkgs.stdenv.mkDerivation {
    pname = "comfy-ui";
    version = versions.comfyui.version;

    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;

    nativeBuildInputs = [ pkgs.makeWrapper ];

    installPhase = ''
      mkdir -p $out/bin
      ln -s ${comfyUiLauncher}/bin/comfy-ui $out/bin/comfy-ui
    '';

    passthru = {
      inherit
        comfyuiSrc
        pythonRuntime
        modelDownloaderDir
        frontendRoot
        ;
      version = versions.comfyui.version;
    };

    meta = with lib; {
      description = "ComfyUI - A powerful and modular diffusion model GUI";
      homepage = "https://github.com/comfyanonymous/ComfyUI";
      # ComfyUI is GPL-3.0; bundled custom nodes have various licenses
      license = with licenses; [
        gpl3 # ComfyUI, Impact Pack, KJNodes
        agpl3Only # bitsandbytes-NF4
        mit # rgthree-comfy, Florence2, MMAudio
        asl20 # GGUF, LTXVideo, x-flux, PuLID, WanVideoWrapper
      ];
      platforms = platforms.linux ++ platforms.darwin;
      maintainers = [
        {
          name = "James Brink";
          github = "utensils";
        }
      ];
      mainProgram = "comfy-ui";
    };
  };

  dockerLib = import ./docker.nix { inherit pkgs lib versions; };

  dockerImage = dockerLib.mkDockerImage {
    name = "comfy-ui";
    tag = "latest";
    comfyUiPackage = comfyUiPackage;
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
    };
  };

  dockerImageCuda = dockerLib.mkDockerImage {
    name = "comfy-ui";
    tag = "cuda";
    comfyUiPackage = comfyUiPackage;
    cudaSupport = true;
    cudaVersion = "cu124";
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
      "com.nvidia.volumes.needed" = "nvidia_driver";
    };
  };
in
{
  default = comfyUiPackage;
  inherit
    dockerImage
    dockerImageCuda
    pythonRuntime
    comfyuiSrc
    modelDownloaderDir
    frontendRoot
    ;
}
