name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Explain why this would be valuable...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: If you have ideas on how this could be implemented, share them here
      placeholder: Optional implementation details...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) does this feature apply to?
      multiple: true
      options:
        - Linux (x86_64)
        - Linux (aarch64)
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Docker
        - All platforms
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: Links, screenshots, related issues...
    validations:
      required: false
