#!/usr/bin/env bash
#
# Update template input files for ComfyUI workflow templates
#
# This script fetches the manifest of template input files from the official
# Comfy-Org repository and generates a Nix file with all the inputs pre-hashed.
# This enables pure, reproducible Nix builds without runtime downloads.
#
# Usage:
#   ./scripts/update-template-inputs.sh
#
# Output:
#   nix/template-inputs.nix - Generated Nix file with all template inputs
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
detail() { echo -e "    ${CYAN}-${NC} $1"; }

# Configuration
MANIFEST_URL="https://raw.githubusercontent.com/Comfy-Org/workflow_templates/main/workflow_template_input_files.json"
OUTPUT_FILE="nix/template-inputs.nix"
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

# Change to repo root
cd "$(dirname "$0")/.."

echo ""
echo "================================================"
echo "  Template Inputs Update Script"
echo "================================================"
echo ""

# Check dependencies
for cmd in curl jq nix-prefetch-url python3; do
    if ! command -v "$cmd" &> /dev/null; then
        error "Required command '$cmd' not found. Please install it."
    fi
done

# Fetch the manifest
info "Fetching template inputs manifest..."
MANIFEST_FILE="$TEMP_DIR/manifest.json"
if ! curl -fsSL "$MANIFEST_URL" -o "$MANIFEST_FILE"; then
    error "Failed to fetch manifest from $MANIFEST_URL"
fi

# Count total files (manifest has .assets array)
TOTAL_FILES=$(jq '.assets | length' "$MANIFEST_FILE")
success "Found ${BOLD}$TOTAL_FILES${NC} template input files"
echo ""

# Start generating the Nix file
info "Generating nix/template-inputs.nix..."
GENERATED_FILE="$TEMP_DIR/template-inputs.nix"

cat > "$GENERATED_FILE" << 'HEADER'
# Template input files for ComfyUI workflow templates
#
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/update-template-inputs.sh
#
# These are input files (images, audio, etc.) referenced by workflow templates.
# They are fetched at Nix build time for reproducible, pure builds.
#
{ pkgs }:
let
  # All template input files with their URLs and hashes
  inputFiles = {
HEADER

# Process each file in the manifest
PROCESSED=0
FAILED=0
FAILED_FILES=""

while IFS= read -r entry; do
    FILE_PATH=$(echo "$entry" | jq -r '.file_path')
    URL=$(echo "$entry" | jq -r '.url')

    # Extract just the filename (strip "input/" prefix if present)
    FILENAME=$(basename "$FILE_PATH")

    # Percent-encode only the URL basename (handles spaces, &, etc.)
    URL_BASENAME=$(basename "$URL")
    URL_PREFIX=${URL%"$URL_BASENAME"}
    URL_BASENAME_ENC=$(python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))' "$URL_BASENAME")
    URL_ENC="${URL_PREFIX}${URL_BASENAME_ENC}"

    # Ensure nix-prefetch-url store name is valid (no spaces/%/etc)
    SAFE_NAME=${FILENAME//[!A-Za-z0-9+._?=-]/_}

    # Skip if URL is null or empty
    if [[ -z "$URL" || "$URL" == "null" ]]; then
        warn "Skipping $FILENAME - no URL"
        continue
    fi

    PROCESSED=$((PROCESSED + 1))
    printf "\r  [%d/%d] Fetching hash for %s..." "$PROCESSED" "$TOTAL_FILES" "$FILENAME"

    # Fetch the hash using nix-prefetch-url
    # The --type sha256 flag ensures we get SRI format
    if HASH=$(nix-prefetch-url --type sha256 --name "$SAFE_NAME" "$URL_ENC" 2>/dev/null); then
        # Convert to SRI format (sha256-base64)
        SRI_HASH=$(nix hash to-sri --type sha256 "$HASH" 2>/dev/null || echo "sha256-$HASH")

        # Write the entry (properly escape the filename for Nix attribute names)
        # Use quotes for filenames with special characters
        cat >> "$GENERATED_FILE" << EOF
    "$FILENAME" = {
      url = "$URL_ENC";
      hash = "$SRI_HASH";
    };
EOF
    else
        FAILED=$((FAILED + 1))
        FAILED_FILES="$FAILED_FILES\n    - $FILENAME"
    fi
done < <(jq -c '.assets[]' "$MANIFEST_FILE")

# Clear the progress line
printf "\r%80s\r" ""

# Close the inputFiles attrset and add the derivation
cat >> "$GENERATED_FILE" << 'FOOTER'
  };

  # Fetch all input files and create derivations
  fetchedInputs = pkgs.lib.mapAttrsToList (name: spec: {
    inherit name;
    src = pkgs.fetchurl {
      inherit (spec) url hash;
    };
  }) inputFiles;
in
pkgs.runCommand "comfyui-template-inputs"
  {
    passthru = {
      # Expose the count for debugging/info
      fileCount = builtins.length fetchedInputs;
      # Expose individual files for selective access
      files = inputFiles;
    };
  }
  ''
    mkdir -p $out/input
    ${pkgs.lib.concatMapStrings (file: ''
      ln -s ${file.src} "$out/input/${file.name}"
    '') fetchedInputs}
  ''
FOOTER

# Move generated file to final location
mv "$GENERATED_FILE" "$OUTPUT_FILE"

echo ""
success "Generated ${BOLD}$OUTPUT_FILE${NC}"
echo ""
info "Statistics:"
echo "    Total files in manifest: $TOTAL_FILES"
echo "    Successfully processed:  $((PROCESSED - FAILED))"
if [[ $FAILED -gt 0 ]]; then
    echo "    Failed to fetch:         $FAILED"
    warn "Failed files (likely URL encoding issues):"
    echo -e "$FAILED_FILES" | while read -r line; do
        [[ -n "$line" ]] && detail "$line"
    done
fi
echo ""

# Remind to git add
echo "================================================"
echo "  Update Complete!"
echo "================================================"
echo ""
info "Next steps:"
echo "    1. Review the generated file: git diff $OUTPUT_FILE"
echo "    2. Stage the changes: git add $OUTPUT_FILE"
echo "    3. Test the build: nix build"
echo ""
